{
 "title": "Nginx ingress connections counter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "throughput", "label": "Throughput >", "query": "1,10,30,50,100,150" },
   { "name": "IP", "label": "Filter by IP" }
  ]
 },
 "panels": [
  {
   "title": "Total connections per second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(nginx_connections_by_remote_addr[5m]))"
    }
   ]
  },
  {
   "title": "Top 5 Producer",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (remote_addr,pod) (rate(nginx_connections_by_remote_addr[5m])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Nginx connections per second",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (remote_addr,pod) (rate(nginx_connections_by_remote_addr{remote_addr=~\"$IP.*\"}[5m]) > $throughput)",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  }
 ]
}